### PR TITLE
Updated CaliberX, PADO Tags and Patches; Added ISFX, MMM Helper Patch, Fixed YUP-GT Load After and Tags

### PR DESCRIPTION
**Pull request by darthbdaman**
Updated CaliberX, PADO Tags and Patches; Added ISFX, MMM Helper Patch,
Fixed YUP-GT Load After and Tags

### CODE REVIEW

**Comment by Ortham** [comment]
@Freso, @Sharlikran you both know more about Fallout: NV than me, I think. Does this look OK to you?

**Comment by Sharlikran** [comment]
I have not used any of those mods and the changes don't look like they would cause an issue.  I don't know that I would be able to check them because of some of the dependencies .  Specifically it would take some time to set up [TTW](https://taleoftwowastelands.com/) since it requires copying Fallout 3 files to the Fallout NV folder.

For non TTW files it might be a good idea to verify any Delev and Relev tags at least.  Fireundubh made a script for bash tag suggestions.  I don't know whether or not that was used. If it was used it is still recommended to check the results in FNVEdit after the xEdit report.

Did you use that script or have you been modding for a while @darthbdaman and you know what tags to apply?

One note though.  The current working [Wrye Flash for Fallout New Vegas](http://www.nexusmods.com/newvegas/mods/35003/?) doesn't have, and won't be updated to have LOOT support.  So any Bash Tag suggestions have to be applied manually.  If you chose to merge the pull request without any kind of verification it wouldn't really hurt anything and the tags could always be changed.

**Comment by darthbdaman** [comment]
I use the script, then I check them and make sure they make sense.

They are mostly my mods, so I am confident they are the right tags

**Comment by Sharlikran** [comment]
Well if you at least verified what the script reported then since most of the mods are yours I don't see why it couldn't be merged.

Wrinkly, the xEdit report does list why xEdit feels the tag should be used.  You can even click the FormID and easily jump to the record for the tag suggestions.  It's a pretty [good script](https://github.com/fireundubh/xedit/blob/master/all/Generate%20Tags%20for%20Wrye%20Bash.pas).

**Pull request merged**
