### PR TITLE
Add ENBSeries

### PR DESCRIPTION
**Pull request by Superfly-Johnson**
Similarly to the previous PR, ENBSeries is effectively obsolete of rnew vegas. People should use Reshade and more modern plugins instead

### CODE REVIEW

**Comment by pStyl3** [comment]
The `obsolete` message advises the user to update to the latest version, so it's not exactly fit for what the intention of this PR is.

That being said, I think that we need to decline this PR, as ENBSeries vs Reshade is not an objective thing - it's subjective and you will find people from both sides thinking that the one or the other is better.

**Comment by Superfly-Johnson** [comment]
ENBSeries conflicts with New Vegas Tick Fix and New Vegas Heap Replacer, both of which are considered essential mods for new vegas. Most of the new vegas community thinks ENBSeries is obsolete and dangerous to use with a modern install

**Comment by WilliamImm** [comment]
Suggestion: mark ENBSeries as incompatible with New Vegas Tick Fix and New Vegas Heap Replacer, instead of marking it as obsolete. This should keep the subjectivity of it vs ReShade out and focus on the objectivity, which is that it's incompatible with these mentioned mods.

Most would go and keep Tick Fix and Heap Replacer anyways due to their benefits and modern modding recs anyways.

EDIT: Mind, this should be a new message anchor regardless of what we do.

**Comment by Superfly-Johnson** [comment]
ENBSeries for New Vegas hasn't been updated since 2014 and hasn't ever been completed. It's not a matter of subjective as it would be for Skyrim or SkyrimSE where ENB is both feature complete and stable, it's a matter of it just hasn't kept up with the rest of the modding community and frankly shouldn't be used anymore as better and more specialized mods exist already

**Comment by pStyl3** [comment]
If ENBSeries is conflicting with New Vegas Tick Fix and New Vegas Heap Replacer, it is making these mods incompatible to one another - but in my opinion this does not warrant declaring ENBSeries obsolete and a general advise to use Reshade instead. 

I think @WilliamImm's idea might be the best approach. Therefore I'm gonna open an issue for that and close this PR without merging.

**Pull request closed without merging**
